services:
  app:
    build: .
    image: service-backend
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      # - POSTGRES_DATABASES=dev,test
    ports:
      - "5432:5432"
